### ISSUE TITLE
Basic Footer creation.

### ISSUE THREAD

**Issue by atulraj85** [aayushjoshi2709/the_big_O_community#7]

**Comment by atulraj85** [comment]
![Screenshot from 2023-12-15 09-22-37](https://github.com/aayushjoshi2709/the_big_O_community/assets/121156542/558824fd-f1fc-4597-9189-bb51aa48e967)

**Comment by atulraj85** [comment]
Aaisa footer bhi bana dena @aayushjoshi2709

**Comment by aayushjoshi2709** [comment]
done
